// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_rutas_Character_id_ from "./routes/(rutas)/Character/[id].tsx";
import * as $_rutas_Characters from "./routes/(rutas)/Characters.tsx";
import * as $_rutas_Favoritos from "./routes/(rutas)/Favoritos.tsx";
import * as $_rutas_House_casa_ from "./routes/(rutas)/House/[casa].tsx";
import * as $_rutas_Profile from "./routes/(rutas)/Profile.tsx";
import * as $_rutas_Search from "./routes/(rutas)/Search.tsx";
import * as $_rutas_middleware from "./routes/(rutas)/_middleware.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $CharactersIsland from "./islands/CharactersIsland.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $ProfileIsland from "./islands/ProfileIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(rutas)/Character/[id].tsx": $_rutas_Character_id_,
    "./routes/(rutas)/Characters.tsx": $_rutas_Characters,
    "./routes/(rutas)/Favoritos.tsx": $_rutas_Favoritos,
    "./routes/(rutas)/House/[casa].tsx": $_rutas_House_casa_,
    "./routes/(rutas)/Profile.tsx": $_rutas_Profile,
    "./routes/(rutas)/Search.tsx": $_rutas_Search,
    "./routes/(rutas)/_middleware.tsx": $_rutas_middleware,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/CharactersIsland.tsx": $CharactersIsland,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/ProfileIsland.tsx": $ProfileIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
